version: "3"
services: 
    api:
        image: librarybackend:test
        ports: 
          - "5000:5000"
    apitest:
        image: librarybackend:test
        depends_on: 
          - api
        command: 
          - "./scripts/wait-for-it.sh"
          - "api:5000"
          - "-t"
          - "0"
          - "--"
          - "pytest"
          - "./tests"
        environment: 
          - FLASK_TEST_SERVER=api
          - FLASK_TEST_PORT=5000
        