version: "3"
services: 
    api:
        image: librarybackend:test
        ports: 
          - "5000:5000"
    testrunner:
        image: libraryfrontend:test
        depends_on: 
            - api
        command: 
            - "./scripts/wait-for-it.sh"
            - "api:5000"
            - "-t"
            - "0"
            - "--"
            - "npm"
            - "run"
            - "test:e2e"
        
        